const slides=[...document.querySelectorAll('.slide')];let current=0,step=0;const names=slides.map(s=>s.dataset.name);const nav=document.querySelector('footer nav');
slides.forEach((s,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`Frame ${i+1}: ${names[i]}`);b.dataset.frame=i;b.onclick=()=>show(i);nav.append(b)});
const maxStep=()=>Math.max(0,...[...slides[current].querySelectorAll('.fragment')].map(e=>+e.dataset.step));
function pauseHiddenVideos(){document.querySelectorAll(".slide video").forEach(v=>{if(v.closest(".slide").hidden||v.closest(".fragment")?.getAttribute("aria-hidden")==="true")v.pause()})}
function refresh(){slides[current].querySelectorAll('.fragment').forEach(e=>{const visible=e.dataset.hot==='true'?step>=+e.dataset.step&&step<=+(e.dataset.until||e.dataset.step):+e.dataset.step<=step;e.classList.toggle('revealed',visible);e.setAttribute('aria-hidden',!visible);e.inert=!visible});if(slides[current].dataset.scene==='trajectory-intro'){
 const descriptions=['Schematic of trajectory space.','A helicopter trajectory records how its state evolves over time.','State and control-command histories together describe a helicopter trajectory.','Each sample point represents one complete helicopter movement, including state and control variables over time.','The teal feasible set contains trajectories satisfying aircraft dynamics and actuator limits.'];
 document.getElementById('intro-factor-space-desc').textContent=descriptions[step]||descriptions[4];
}if(slides[current].dataset.scene==='factorization'){
 const descriptions=['Schematic of feasible motion and its proposed factorization.','The physically executable region highlights the challenge of learning coupled motion structure.','One feasible motion maps through an encoder into all latent factors. Illustrative meanings are path variation, body rotation and pace variation; residual physical coupling is retained.'];
 document.getElementById('factor-space-desc').textContent=descriptions[step>=4?2:step>0?1:0];
}pauseHiddenVideos();document.querySelector('#previous').disabled=current===0&&step===0;document.querySelector('#next').disabled=current===slides.length-1&&step===maxStep();document.querySelector('.progress').style.width=((current+(step/maxStep()))/slides.length*100)+'%';document.querySelector('#announcement').textContent=`Frame ${current+1}: ${names[current]}. Step ${step} of ${maxStep()}.`;drawAll();}
function show(i,last=false){current=Math.max(0,Math.min(slides.length-1,i));step=last?maxStep():0;slides.forEach((s,j)=>{s.hidden=j!==current;s.classList.toggle('active',j===current);s.scrollTop=0});document.body.classList.toggle('on-light',slides[current].classList.contains('light'));nav.querySelectorAll('button').forEach((b,j)=>{b.classList.toggle('active',j===current);if(j===current)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});document.querySelector('#counter').textContent=`0${current+1} / ${String(slides.length).padStart(2,"0")}`;document.querySelector('#frame-name').textContent=names[current];history.replaceState(null,'',`#${current+1}`);refresh();}
function next(){if(step<maxStep()){step++;refresh()}else if(current<slides.length-1)show(current+1)}function prev(){if(step>0){step--;refresh()}else if(current>0)show(current-1,true)}document.querySelector('#next').onclick=next;document.querySelector('#previous').onclick=prev;
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.target.matches('input,select,video,a')||e.key===' '&&e.target.matches('button'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();next()}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();prev()}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1,true);if(e.key.toLowerCase()==='f')document.querySelector('#fullscreen').click()});
document.querySelector('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.querySelector('#announcement').textContent='Full screen is unavailable in this browser.'}};
function open(id){document.querySelector(id).showModal()}document.querySelector('#video-open')?.addEventListener('click',()=>open('#video-dialog'));document.querySelectorAll('[data-replay]').forEach(b=>b.onclick=()=>{const v=document.getElementById(b.dataset.replay);v.currentTime=0;v.play().catch(()=>{document.querySelector('#announcement').textContent='Use the video play control to start the clip.'})});document.querySelector('#reconstruction-open')?.addEventListener('click',()=>open('#reconstruction-dialog'));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>d.querySelector('video')?.pause());d.onclick=e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}});
const comparisonVideos=['feasible-video','circle-video'].map(id=>document.getElementById(id));
function updateBothLabel(){document.getElementById('play-both').textContent=comparisonVideos.every(v=>!v.paused&&!v.ended)?'Ⅱ Pause both':'▶ Play both'}
async function startBoth(restart=false){if(restart)comparisonVideos.forEach(v=>{v.currentTime=0});const results=await Promise.allSettled(comparisonVideos.map(v=>v.play()));if(results.some(r=>r.status==='rejected'))document.getElementById('announcement').textContent='Use the individual video controls if playback is unavailable.';updateBothLabel()}
document.getElementById('play-both').onclick=()=>{if(comparisonVideos.every(v=>!v.paused&&!v.ended)){comparisonVideos.forEach(v=>v.pause())}else{if(comparisonVideos.some(v=>v.ended))startBoth(true);else startBoth()}updateBothLabel()};
document.getElementById('replay-both').onclick=()=>startBoth(true);
comparisonVideos.forEach(v=>['play','pause','ended'].forEach(event=>v.addEventListener(event,updateBothLabel)));
function drawAll(){}
show(Math.max(0,Math.min(slides.length-1,(parseInt(location.hash.slice(1))||1)-1)));
